version: "3.7"
x-golang-daemon: &golang-daemon
  image: varunpatil/cosmos:0.1.0
  depends_on:
    - postgresql
    - temporal
  environment:
    WAIT_HOSTS: postgresql:5432, temporal:7233
    WAIT_TIMEOUT: 120
    WAIT_AFTER: 10
    ARTIFACT_DIR: ${ARTIFACT_DIR}
    SCRATCH_SPACE: ${SCRATCH_SPACE}
    LOCAL_DIR: ${LOCAL_DIR}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${ARTIFACT_DIR}:/tmp/cosmos/artifacts
    - ${SCRATCH_SPACE}:/tmp/cosmos/scratch
    - ${LOCAL_DIR}:/tmp/cosmos/local
services:
  postgresql:
    container_name: cosmos-postgresql
    environment:
      POSTGRES_PASSWORD: password
    image: postgres:9.6
    networks:
      - cosmos-network
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  temporal:
    container_name: cosmos-temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=password
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    image: varunpatil/temporal-auto-setup:1.10.5
    command: autosetup
    networks:
      - cosmos-network
    ports:
      - 7233:7233
  temporal-web:
    container_name: cosmos-temporal-web
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web:1.10.0
    networks:
      - cosmos-network
    ports:
      - 8088:8088
  cosmos:
    container_name: cosmos
    <<: *golang-daemon
    command: sh -c '/wait && /cosmosd'
    networks:
      - cosmos-network
    ports:
      - 5000:5000
  cosmos-worker:
    container_name: cosmos-temporal-worker
    <<: *golang-daemon
    command: sh -c '/wait && /temporald'
    networks:
      - cosmos-network
networks:
  cosmos-network:
volumes:
  postgres-data:
